#!/usr/bin/env bash

#  Copyright 2024 Birchfox project contributors
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# https://www.shellcheck.net/wiki/SC2207

# install to "${BASH_COMPLETION_USER_DIR:-"${XDG_DATA_HOME:-"$HOME/.local/share"}/bash-completion"}/completions"

_bfox() {
  local current="$2" previous="$3"

  local options="-s --service-name -h --help"
  local non_composable_commands="deploy start stop restart enable disable status"

  case "${previous}" in
    -s|--service-name)
      ;&
    -h|--help)
      return
      ;;
    deploy)
      mapfile -t COMPREPLY < <(compgen -o default -- "$current")
      return
      ;;
    start|stop|restart|enable|disable|status)
      return
      ;;
    log)
      mapfile -t COMPREPLY < <(compgen -W "${non_composable_commands}" -- "$current")
      return
      ;;
  esac

  mapfile -t COMPREPLY < <(compgen -W "${options} ${non_composable_commands} log" -- "$current")
}

complete -F _bfox bfox
