#!/usr/bin/env bash

# https://www.shellcheck.net/wiki/SC2207

# install to "${BASH_COMPLETION_USER_DIR:-"${XDG_DATA_HOME:-"$HOME/.local/share"}/bash-completion"}/completions"

_oak() {
  local current="$2" previous="$3"

  local options="-s --service-name -h --help"
  local non_composable_commands="deploy start stop restart enable disable status"

  case "${previous}" in
    -s|--service-name)
      ;&
    -h|--help)
      return
      ;;
    deploy)
      mapfile -t COMPREPLY < <(compgen -o default -- "$current")
      return
      ;;
    start|stop|restart|enable|disable|status)
      return
      ;;
    log)
      mapfile -t COMPREPLY < <(compgen -W "${non_composable_commands}" -- "$current")
      return
      ;;
  esac

  mapfile -t COMPREPLY < <(compgen -W "${options} ${non_composable_commands} log" -- "$current")
}

complete -F _oak oak
